# 2018-12-22 (cc) <paul4hough@gmail.com> -*- yaml -*-
#
---
groups:
  - name: exporter-down
    rules:
      - alert: exporter-down
        expr: up == 0
        for: 5m
        annotations:
          description: >-
            exporter {{ $labels.job }} down
