# 2019-01-28 (cc) <paul4hough@gmail.com>
#
---

- name: create {{ consul_user }} user
  become: true
  user:
    name: "{{ consul_user }}"
    home: "{{ consul_cfg_dir }}"
    system: true

- name: upload consul
  become: true
  copy:
    src: bin/consul
    dest: "{{ bin_dir }}/consul"
    mode: 0775

- name: consul cfg & data dirs
  become: true
  file:
    name: "{{ item }}"
    state: directory
    mode: 0775
    owner: "{{ consul_user }}"
    group: "{{ consul_group }}"
  loop:
    - "{{ consul_cfg_dir }}"
    - "{{ consul_data_dir }}"

- name: install {{ consul_cfg_dir }} files
  become: true
  become_user: "{{ consul_user }}"
  template:
    src: consul.d/{{ item }}.j2
    dest: "{{ consul_cfg_dir }}/{{ item }}"
    mode: 0640
  loop:
    - 00-consul.json
  notify:
    - consul reload

- name: install consul services files
  become: true
  template:
    src: systemd/consul.service.j2
    dest: /etc/systemd/system/consul.service


- name: consul service
  become: true
  systemd:
    name: consul
    state: started
    enabled: true
    daemon_reload: true
