# 2019-02-06 (cc) <paul4hough@gmail.com>
#
---
- name: create {{ prom_user }} user
  become: true
  user:
    name: "{{ prom_user }}"
    home: "{{ prom_data_dir }}"
    system: true

- name: upload node_exporter
  become: true
  copy:
    src: bin/node_exporter
    dest: "{{ sbin_dir }}/node_exporter"
    mode: 0775

- name: install consul node exporter service
  become: true
  become_user: "{{ consul_user }}"
  template:
    src: consul.d/{{ item }}.j2
    dest: "{{ consul_cfg_dir }}/{{ item }}"
    mode: 0640
  loop:
    - 10-node-exp.json
  notify:
    - consul reload

- name: install node_exporter services files
  become: true
  template:
    src: systemd/node_exporter.service.j2
    dest: /etc/systemd/system/node_exporter.service

- name: enable and start node_exporter service
  become: true
  systemd:
    name: node_exporter
    state: started
    enabled: true
    daemon_reload: true
